name: GitsLibrary

packages:
  - packages/**

scripts:
  lint:
    run: melos run analyze && melos run format:exit-if-changed
    description: Run all static analysis checks

  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
        - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  
  format:
    run: flutter format .
    description: |
      Run `flutter format .` in all packages.

  format:exit-if-changed:
    run: flutter format --set-exit-if-changed .
    description: |
      Run `flutter format --set-exit-if-changed .` in all packages.

  clean:all:
    run: melos exec -c 5 -- \
        flutter clean
  
  get:
    run: melos exec -c 3 -- \
        flutter packages get

  test:
    run: melos exec -c 3 -- \
        flutter test

  build:runner:
    run: melos exec -c 1 -- \
        flutter pub run build_runner build --delete-conflicting-outputs

  upgrade:major:
    run: |
      melos exec -c 5 -- \
        flutter pub upgrade --major-versions
    description: |
      Run `flutter pub upgrade --major-versions` in all packages.
        - Note: this is can make break change for all package.
  upgrade:
    run: |
      melos exec -c 5 -- \
        flutter pub upgrade
    description: |
      Run `flutter pub upgrade' in all packages.