name: gits_strapi
description: this library is used to facilitate integration with Strapi there are several main functions such as GET collection, single, and CRUD besides that we also provide several helpers to make it easier to use.
version: 1.0.1
homepage: https://gits.id/
repository: https://github.com/gitsindonesia/flutter-library/tree/main/packages/gits_strapi

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  gits_http: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
